version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  groups:
    maven:
      patterns:
        - "*"
  ignore:
    - dependency-name: org.codehaus.plexus:plexus-xml
      versions:
      - ">=4.0.0"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  groups:
    github-actions:
      patterns:
        - "*"
